// @file ShaderVectorField.h
// @author Generated by PSL

#ifndef ShaderVectorField_H
#define ShaderVectorField_H

#include "Particles.h"
#include "ParticleShader.h"
#include "VectorField.h"

class ShaderVectorField: public ParticleShader
{
public:
	MAKE_PARTICLESTUFF_NAME();

	VectorField *vf;
	
	// parameters
	double scaler;
	double drawStartPoints;

	// parameter function calls
	int qlen();
	void getq(double *q);
	void setq(double *q);
	void qname(char **qn);

	// constuctor
	ShaderVectorField(Particles *ps=NULL);

	void attachAttributes();
	// draw
	void draw(int s);
};
#endif
