#ifndef PLANE_PIXMAP_H
#define PLANE_PIXMAP_H

static const char* const plane_pixmap16[] = { 
"16 16 46 1",
". c None",
"j c #26267d",
"C c #27277e",
"K c #28287e",
"O c #2e2e81",
"x c #2f2f81",
"m c #303081",
"g c #353583",
"s c #363684",
"B c #383885",
"f c #3f3e88",
"H c #47468b",
"p c #47468c",
"G c #49488c",
"e c #4f4e8f",
"k c #545391",
"J c #5c5b94",
"d c #5f5d96",
"v c #666499",
"r c #6c6b9b",
"c c #6f6d9d",
"N c #706f9d",
"L c #7776a0",
"b c #7e7ca3",
"A c #817fa4",
"n c #8482a6",
"a c #8c8aa9",
"F c #9593ad",
"y c #9694ae",
"u c #9794ae",
"i c #9a97af",
"# c #a5a2b4",
"P c #a8a4b5",
"I c #a9a6b6",
"q c #b4b1ba",
"w c #b9b6bc",
"l c #bbb8bd",
"M c #bcb8be",
"D c #c4c1c1",
"z c #c8c4c3",
"Q c #c9c5c3",
"h c #cecac6",
"o c #cecbc6",
"E c #d0cdc7",
"R c #d1cdc7",
"t c #d3cfc8",
"................",
"................",
"................",
"......#abcdefgh.",
".....ijjjjjjjk..",
"....lmjjjjjjjn..",
"...opjjjjjjjjq..",
"...rjjjjjjjjst..",
"..ujjjjjjjjjv...",
".wxjjjjjjjjjy...",
".zABjjjjjjjCD...",
"...EFGjjjjjH....",
"......IJKjjL....",
"........MNOP....",
"..........QR....",
"................"};

static const char* const plane_pixmap32[] = { 
"32 32 83 2",
"Qt c None",
".q c #26267d",
".u c #27277d",
".G c #27277e",
".p c #28287e",
".B c #29297e",
".2 c #2a2a7f",
".1 c #2b2b7f",
"#f c #2e2d80",
".S c #2f2f81",
".M c #303082",
".o c #313182",
".j c #323282",
"#g c #333283",
".x c #343483",
".6 c #353584",
"#k c #373684",
".r c #3b3a86",
".n c #3e3d87",
".V c #3f3e88",
".i c #414089",
"#. c #45448b",
"#n c #47468b",
".U c #49488c",
".L c #4a498d",
".m c #4b4a8d",
".A c #4d4c8e",
".E c #4e4c8e",
".7 c #4e4d8f",
".h c #515090",
".Y c #545391",
"#b c #585793",
".O c #5c5b95",
".g c #5f5d96",
"#l c #626197",
".0 c #686699",
".v c #6a699b",
"#e c #6b699b",
".W c #6d6b9c",
".f c #6e6d9c",
".N c #716f9d",
".D c #72719e",
".H c #7a78a2",
".5 c #7d7ba3",
"#j c #7f7da4",
"## c #807ea4",
".e c #8280a5",
".l c #8c8aa9",
".Q c #8e8caa",
".d c #908eab",
".9 c #918fab",
"#o c #9390ac",
"#m c #9592ad",
".y c #9997af",
".P c #9b99b0",
".c c #9d9bb0",
".F c #9d9bb1",
".t c #a09db2",
".X c #a29fb2",
"#a c #a4a1b3",
"#p c #a7a4b5",
".J c #aca8b7",
".b c #afabb8",
"#c c #b1aeb9",
".Z c #b5b2bb",
"#d c #b7b4bc",
".k c #bbb8be",
".R c #bcb8be",
".I c #bdbabe",
".w c #bfbbbf",
".a c #c0bdc0",
".4 c #c5c1c2",
"#q c #c6c2c2",
"#i c #c6c3c2",
".C c #c7c3c3",
".3 c #cbc7c4",
".8 c #cdc9c5",
".# c #cdcac5",
".T c #cecbc6",
".K c #cfcbc6",
".z c #d0ccc6",
"#h c #d2cec7",
".s c #d3cfc8",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt.#.a.b.c.d.e.f.g.h.i.j.kQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQt.l.g.m.n.o.p.q.q.q.q.q.q.q.q.q.r.sQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQt.t.u.q.q.q.q.q.q.q.q.q.q.q.q.q.q.vQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQt.w.x.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.yQtQtQtQt",
"QtQtQtQtQtQtQtQtQt.z.A.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.B.CQtQtQtQt",
"QtQtQtQtQtQtQtQtQt.D.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.EQtQtQtQtQt",
"QtQtQtQtQtQtQtQt.F.G.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.HQtQtQtQtQt",
"QtQtQtQtQtQtQt.I.j.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.JQtQtQtQtQt",
"QtQtQtQtQtQt.K.L.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.M.KQtQtQtQtQt",
"QtQtQtQtQtQt.N.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.OQtQtQtQtQtQt",
"QtQtQtQtQt.P.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.QQtQtQtQtQtQt",
"QtQtQtQt.R.S.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.u.kQtQtQtQtQtQt",
"QtQtQt.T.U.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.VQtQtQtQtQtQtQt",
"QtQtQt.W.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.NQtQtQtQtQtQtQt",
"QtQtQt.X.Y.G.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.FQtQtQtQtQtQtQt",
"QtQtQtQtQt.Z.0.1.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.2.3QtQtQtQtQtQtQt",
"QtQtQtQtQtQtQt.4.5.6.q.q.q.q.q.q.q.q.q.q.q.q.q.7QtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQt.8.9#..q.q.q.q.q.q.q.q.q.q.q##QtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQt.s#a#b.G.q.q.q.q.q.q.q.q#cQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQt#d#e#f.q.q.q.q.q#g#hQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt#i#j#k.q.q.q#lQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt.K#m#n.q#oQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt#p#qQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt"};

static const char* const plane_pixmap48[] = { 
"48 48 113 2",
"Qt c None",
".w c #26267d",
".T c #27277d",
".7 c #27277e",
".x c #28287e",
".C c #29297e",
".F c #29297f",
"#H c #2a297f",
".v c #2a2a7f",
"#j c #2b2b7f",
".Z c #2c2c80",
"#t c #2d2d80",
".W c #2e2e80",
"#f c #2f2f81",
"#N c #302f81",
"#o c #323282",
".O c #333282",
".u c #333283",
"#Q c #333383",
".B c #343483",
".h c #3a3986",
"#K c #3a3a86",
".t c #3e3d87",
"#i c #403f88",
".M c #42428a",
"#z c #434289",
".0 c #43428a",
".Q c #44448a",
".A c #46468b",
"#b c #47468b",
".D c #48478b",
".3 c #48478c",
".X c #48488c",
".s c #4a498c",
"#w c #4a4a8d",
"#. c #4b4a8d",
"#v c #4d4c8e",
"#n c #504f8f",
".g c #515090",
".r c #555492",
"#G c #565592",
"#s c #575692",
"#m c #5b5a94",
"#x c #5f5d95",
"#R c #5f5e96",
".f c #636197",
".q c #646398",
"#T c #686699",
".P c #6a699b",
"#a c #716f9d",
"#d c #73719e",
".G c #74729e",
"#J c #74729f",
"#L c #75739f",
".5 c #76749f",
".e c #7876a0",
".J c #7977a1",
".S c #7e7da4",
".2 c #8280a5",
".p c #8583a6",
"#P c #8987a8",
"#p c #8b89a9",
"#M c #8c89a9",
".d c #8e8caa",
"#y c #8f8daa",
".o c #918eab",
".i c #918fac",
".4 c #9492ac",
"#r c #9694ad",
".I c #9794ad",
"#F c #9794ae",
"#g c #9895ae",
"#U c #9b98b0",
".R c #9c99b0",
"#C c #9c9ab0",
".c c #9e9bb1",
".z c #9f9cb1",
".n c #a09db2",
"#c c #a09eb2",
"#O c #a29fb3",
".8 c #a3a0b3",
"#A c #a5a2b4",
".V c #a7a4b5",
".Y c #aba8b6",
".L c #aca9b7",
".m c #adaab7",
"#e c #b1aeb9",
".b c #b2aeb9",
".6 c #b3b0ba",
".N c #b6b3bb",
".l c #b7b4bc",
".E c #b8b5bc",
".y c #bdbabe",
"#I c #bfbbbf",
".U c #bfbcbf",
".1 c #c1bec0",
".k c #c3c0c1",
"## c #c4c0c1",
".K c #c4c1c1",
"#S c #c6c3c2",
"#l c #c7c3c2",
"#k c #c7c4c3",
"#h c #c9c5c3",
"#u c #cac6c4",
".a c #cbc7c4",
"#D c #ccc8c4",
"#q c #ccc8c5",
".j c #cdc9c5",
".9 c #cecac5",
"#E c #cfcbc6",
"#B c #d0ccc7",
".H c #d2cec7",
".# c #d3cfc8",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt.#.a.b.c.d.e.f.g.h.iQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt.#.j.k.l.m.n.o.p.e.q.r.s.t.u.v.w.w.w.w.w.w.x.yQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt.z.A.B.C.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.DQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt.E.F.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.GQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt.H.g.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.IQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt.J.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.C.KQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQt.L.x.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.MQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQt.N.O.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.PQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQt.j.Q.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.RQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQt.S.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.T.UQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQt.V.W.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.X.#QtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQt.Y.Z.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.dQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQt.#.0.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.x.1QtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQt.2.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.3QtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQt.4.v.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.5QtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQt.6.7.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.8QtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQt.9#..w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.x##QtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQt#a.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w#bQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQt#c.7.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w#dQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQt#e#f.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w#gQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQt#h#i.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w#j#kQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQt#l#m.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w#nQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQt.N.e#o.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w#pQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQt#q#r#s.7.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w#t#uQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQt.Y#v.T.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w#wQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQt.L#x.v.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.5QtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQt#h#y#z.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w#AQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt#B#C#i.w.w.w.w.w.w.w.w.w.w.w.w.w.w#j#DQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt#E#F#G#H.w.w.w.w.w.w.w.w.w.w.w.XQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt#I#J#K.w.w.w.w.w.w.w.w.w#LQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt.H#M#N.w.w.w.w.w.w.w#OQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt###P#..w.w.w.w.C##QtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt.Y.P#Q.w#RQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt#S#T#UQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt"};

#endif

